### ISSUE TITLE
doc.save did not populate _id

### ISSUE THREAD

**Issue by u007** [Ivshti/linvodb3#1]
hi, 

im using:
linvodb3 v "3.7.3"

for some reason, doc.save did not saved to ._id (after save event)
```
var doc = new Doc({});
doc['name'] = 'test';
doc.save(function(err) { 
        // Document is saved
        console.log('id: ', doc._id); // return id: undefined
      });
```
please advice

thanks

**Comment by Ivshti** [comment]
Hello, .save creates a new document instance before saving as a default behavior.

You can do this:
```javascript
doc.save(function(err, doc) { 
        // Document is saved
        console.log('id: ', doc._id); // return id: FAtSEAF2bQmBgP5C
      });
```

Although I will fix the issue soon.

**Comment by Ivshti** [comment]
Fixed with commit 4f10216f2147e00a4f6581ae12e3c071aa883820 ! Thank you :)

**Comment by u007** [comment]
awesome man, works great with your sample :+1:

**Comment by Ivshti** [comment]
You no longer need to use my sample, it would work with yours with the latest version - .save now modifies the doc reference you use it with

**Comment by krzysztofantczak** [comment]
So .save creates new records in DB instead of updating the old doc? It seems that's still true in latest version. If so, how can i update my document without creating new record?

**Comment by Ivshti** [comment]
No, it depends on the _id. If the doc has an existing _id it will be updated in place and no new record will be inserted.

**Comment by krzysztofantczak** [comment]
Well, i have some weird situation here. In short:

```
        Virt.findOne({id: data.user.id}, function(err, vir)
        {
            if (! vir     ) vir = new Virt();
            if (! vir.id ) vir.id = data.user.id;

            vir.fsp = 'hhhhhhhhhh';
            vir.save(function(){ ....... });
        });
```
Where - after first update (if user exists) - i'm getting this:

```
    { id: 'nu.75', fsp: 'hhhhhhhhhh', _id: 'yHmM9GaO7OUexPGD' },
    { id: 'nu.75', fsp: 'hhhhhhhhhh', _id: 'zedyhPIwyuXejWHc' }
```

So it seems it creates another instance of the same document.

**Comment by Ivshti** [comment]
The identifying field is _id, not id, for consistency with mongoDB and nedb

**Comment by Ivshti** [comment]
Please use _id as your identifying field

**Comment by krzysztofantczak** [comment]
Why that makes any difference? i'm not treating 'id' as '_id' field - which should be self explanatory here, i'm using it exactly like 'login' or 'username' field. Please read this code again more carefully.

**Comment by Ivshti** [comment]
can you make sure a couple of things 
1) findOne finds an object 
2) you are running the latest version in npm

Just add a console.log(vir, vir && vir._id) right in the beginning of the findOne callback  and see what it logs
