### ISSUE TITLE
TypeError: db is not a function on CentOS

### ISSUE THREAD

**Issue by janteque** [Ivshti/linvodb3#111]
We're getting a very strange behavior that is driving us nuts.

We've created an electron app that uses linvodb. We build the app using electron builder but we're facing a problem when building it for Linux as an AppImage

If we build the app using a CentOS 7.6 the resulting AppImage runs perfectly both in CentOS and in Ubuntu

However, if the app is built using a Bamboo server on RHEL the resulting app works in Ubuntu but in CentOS we are getting this error:

```
Uncaught Exception:
TypeError: db is not a function
    at Function.Model.initStore (/tmp/.mount_WIPO SiboAM3/resources/app.asar/node_modules/linvodb3/lib/model.js:88:115)
    at new Model (/tmp/.mount_WIPO SiboAM3/resources/app.asar/node_modules/linvodb3/lib/model.js:59:35)
    at Object.<anonymous> (/tmp/.mount_WIPO SiboAM3/resources/app.asar/back/models/workspaces.js:20:19)
...
```

Apparently there is no difference between the two servers except the operating system. 

Another hint, when building it using the electronbuilder docker image we are getting the same exception on CentOS

**Comment by Ivshti** [comment]
This usually means an old `leveldown` version; try upgrading it or using `package-lock` to ensure the package versions are the same

**Comment by janteque** [comment]
Thanks for the quick response. We checked the leveldown version used and it is the same (2.1.1). In any case, would this explain that it works on Ubuntu but not in CentOS?

**Comment by Ivshti** [comment]
then it must be some other package version that's different; in any case, it's a dependency issue; try copying package-lock.json from the working installation to the other one and doing an npm install
also verify the version of nodejs is the same

**Comment by janteque** [comment]
I've done as suggested but I still get the same error. Is there a way to track down which dependency is provoking the error? 

I've also build the app using the linux docker container from electron_builder with the same error. This docker image is based on debian. I think it might be related to the rebuild of native dependencies that is done differently in Centos than in Red Hat or in Debian, but I have no way to identify why or how to solve it...
