### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by martpie** [Ivshti/linvodb3#117]
Linvodb is a neat little package, but the last commits were quite some time ago, should we move to something else?

**Comment by Ivshti** [comment]
no, unfortunately it's not maintained but I can't recommend an alternative either - there probably are some out there, if you find any that have similar features/APIs, please let me know and I'll add them to the readme

With that said, it's possible that it's still usable as is, as it was designed to be an interface over LevelUP which lets the underlying backends evolve.

**Comment by martpie** [comment]
Thanks 👍

**Comment by martpie** [comment]
Can we perhaps pin this issue for visibility @Ivshti? 🙏

**Comment by Ivshti** [comment]
done!
