### ISSUE TITLE
[Feature Request] Importing and Exporting

### ISSUE THREAD

**Issue by awsp** [Ivshti/linvodb3#15]
I don't seem to see this feature in the API docs. (Please correct me if I am wrong. :D)

I am constantly working with some data (in csv format) with around 20k~100k rows per file and I would like to insert them into persistent data source using linvodb3 in my Electron App via drag and drop. 
I was wondering if there is such an API to do importing and exporting? 

It would be great if we can also output it back to things like tsv, csv, xml, etc.

Or should I stick with batch insertion instead? (At least for importing)

**Comment by Ivshti** [comment]
Sorry for the late reply - apparently I didn't see the email.

LinvoDB itself does not support an API like this, and it doesn't sound like a feature that should be embedded in the DB to me. One benefit from having it integrated with the DB is to get the mapping in the schema itself - and then use Model.schema to translate the import format into JS properties - but that won't require patching LinvoDB itself.

For importing you can use the .save method, which allows bulk save, and would account for re-saving (updating) objects, unlike insert which only does new inserts.

As for exporting, the best approach would be a streaming cursor - which I'll implement, push and document in a little while.

**Comment by Ivshti** [comment]
Streaming cursors out in 3.10.0:

```javascript
cursor.stream(function(d) { /* document */ }, function(err, res) { /* query is finished, you can still use res */ });
```

Currently very crude, but will help with write-as-we-read data export. 
The real benefit will come with implementing a better streaming cursor API, which doesn't require keeping objects in memory for constructing the final result.

If you're exporting really large amounts of data and this basic streaming cursor implementation overuses memory, you can do better with the internal API cursor.getMatchesStream until a better streaming cursor is implemented.

**Comment by awsp** [comment]
Thanks for your reply. 

Yea, at least for importing, I actually end up writing a little buffer to do bulk insertion. Seems working fine for now. 

I agree that import/export should not be embedded into the DB, as tools like `mysqlimport`, `mongoimport` are also external utility tools. Looks like having a separate utility tool is more appropriate. 
For the current state, streaming cursors should be good enough! 
Thanks for the new version!
