### ISSUE TITLE
deleted document seems to randomly returned

### ISSUE THREAD

**Issue by u007** [Ivshti/linvodb3#2]
Hi,
sorry to disturb again  :-D

ive a scripts that clean up all data,
and query for existing data and check to makesure data returned 0.
and reinsert data from a csv file.
when i do a regex search, it seems to randomly return data together with deleted data.
it happen 50% of the time. im using this with nodewebkit,
and it seems to happen when i refreshed the nodewebkit browser with the exact same query.

```
var LinvoDB = require("linvodb3");
var modelName = "doc";
var schema = { }; // Non-strict always, can be left empty
var options = { filename: 'data/toc.db', store: {db: require('medeadown')} };
var Doc = new LinvoDB(modelName, schema, options); // New model; Doc is the constructor

Doc.remove({}, {multi: true}, function (err, rows) {
  if(err) {
    throw err;
  } else {
    console.log('removed: '+rows +' rows.');
    check_exists_docs();
  }
});

function check_exists_docs() {
  Doc.find({}, function(err, res) {
    console.log('should be empty rows:', res.length);
    res.length.should.eql(0);
    do_import(); //does the insertion
  });
}
```

when i deleted the data directory and reinsert,
its working fine.
i suspect the deleted docs seems to be returned.

the more time i import, the more rows it return.

**Comment by Ivshti** [comment]
Will look into it. Can you check if it's an issue with Medea? The instance is under Doc.store

**Comment by u007** [comment]
how can i check if its medea issue?

**Comment by Ivshti** [comment]
This code will count all the objects in the store:
```
var i = 0; Doc.store.createReadStream().on("data",function(){ i++ }).on("end",function(){console.log(i)})
```

Counting the objects in the back-end store would help debug the issue. Try doing it after every operation and checking if the count is what it's supposed to be.

**Comment by u007** [comment]
i ran the import process from node directly,
the nodewebkit was used purely for read only.
now when i retry again, it seems to be working without any issue.
i can't replicate the same problem now..  

with or without Doc.store.db.db.compact,
it still works nicely,
but with the compact, it seems to clean out the older files in the data folder..

**Comment by Ivshti** [comment]
This is good behaviour. It's supposed to do that. There's no data loss, it just compacts the database.

**Comment by u007** [comment]
could it be that my previous data structure was corrupted?
since ive deleted all the files inside, i think it works great now...

**Comment by Ivshti** [comment]
It's possible. Keep a watch for those things I've mentioned and always console.log / console.error errors in callbacks instead of using `throw`

Can we close this? :)

**Comment by u007** [comment]
alright, thanks man :) :+1:
