### ISSUE TITLE
Why cursor is not an EventEmitter?

### ISSUE THREAD

**Issue by c58** [Ivshti/linvodb3#26]
I think it may be useful, especially with live queries. For now, update of one live query invokes handlers of the same collection for other live queries. It's not good, because any handler can emit a re-render of different parts of the screen or make some hard computations.

P.S. In my project, I've extended Cursor specially for live queries, added some useful features (like optional binding for angular scope for cleanup and digest) and made it EventEmitter for emitting result event. It works great.

**Comment by Ivshti** [comment]
Probably good point. You can PR it. I think if you replace the constructor initialization with an EventEmitter (or extend object with event emitter on init) it would not break anything.

BTW, you should keep in mind linvodb emits events for live queries itself, and I've implemented angular binding like this:
```javascript
LinvoDB.createService = function(module, model, disableScope)
{
    module.factory(model.modelName, ["$rootScope", function($rootScope) 
    {
        if (! refreshScope) refreshScope = _.debounce(function() { if (!$rootScope.playerVisible) $rootScope.$apply() }, 250);
        model.on("liveQueryUpdate", function() { if (!disableScope) refreshScope() });
        return model;
    }]);

};
```
