### ISSUE TITLE
Adhering to Unique parameter

### ISSUE THREAD

**Issue by lokenx** [Ivshti/linvodb3#32]
I'm seeming to have trouble with the `unique` option. Neither of the below options work when inserting duplicate docs (as in the docs get inserted).

```
var Movies = new LinvoDB("movies", {
  title: String,
  id: {
    type: String,
    index: true,
    unique: true
  },
}, {});
```

```
var Movies = new LinvoDB("movies", {
  title: String,
  id: String
}, {});

Movies.ensureIndex({ fieldName: "id", unique: true })
```

**Comment by Ivshti** [comment]
Several questions

1. Why are you using a separate id property when there is the default _id - by default unique, and you can use any value. I've seen a few more users do it and it just seems weird

2. can you post example code so I can see what's the exact aprt that doesn't work, what error it emits/doesn't emit/etc?

**Comment by lokenx** [comment]
1. It's really just shorthand for using `tmdbid`/`tmdb_id` or something. I need to be able to reference it against an external DB/API. I still use `_id` for my own DB when possible

 2.  I will when I get a chance later today. It's not emitting any errors, when it should be emitting something regarding duplicate entries etc.

**Comment by lokenx** [comment]
Huh, so while putting together a barebones db it seems to be working. It requires both

```
index: true,
unique: true
```

but seems to be working now... I refactored my code so many times I can't get back to the state where it wasn't working so I must have done something funky somewhere.

Thanks for awesome db!

**Comment by Ivshti** [comment]
That makes sense.

Yes, you have to set both index/unique in the model or ensureIndex
