### ISSUE TITLE
why no one want a promise version

### ISSUE THREAD

**Issue by klausgao** [Ivshti/linvodb3#38]
good job dude. and it is really very fast, more than mongodb.
and I think most people don't like callback, so why we don't have a promise support?

**Comment by klausgao** [comment]
just like mongoose, .exec() will give us a promise.

**Comment by Ivshti** [comment]
Good idea - I'll add it on the roadmap, but I don't have any time to work on that. PRs are welcome

**Comment by klausgao** [comment]
After 2 days' research, I finally find a very good method to make your linvodb3 to work with tj's co.
let me show here: http://bluebirdjs.com/docs/api/promise.promisify.html
my code is below:
```
var Promise1 = require("bluebird");
var testInsert = Promise1.promisify(Doc.insert, {context: Doc});
router.get('/linvodb3Insert2', function (req, res) {
    co(function*() {
        yield testInsert(
            {
                string1: 'LinvoDB' + randomize('A', 20),
                number1: _.now(),
                indexID: 0
            }
        );
        return res.json({msg: 'success'});
    }).catch(function (err) {
        return res.json({msg: 'err'});
    });
});
```

I have tried tj's node-thunkify, co-thunkify, thunkify-wrap and some others libs, very weird, they all can't work.
finally I know I was missing the context, and use the bluebird to finish it.

**Comment by lamanabie** [comment]
You can use bluebird `promisifyAll` function to transform all callback functions to Promises. But can call original functions aswell
```javascript
ModelTest.find({}, (err, docs) => {

})
``` 
or you use functions with suffix `Async` that return Promise 
```javascript
ModelTest.findAsync({})
   .then((docs) => {
      console.log(docs)
   })
```
Example
----
```javascript
const bluebird = require('bluebird')
const LinvoDB = require("linvodb3")

LinvoDB.dbPath = process.cwd()
const ModelTest = new LinvoDB('test', {}, {})

bluebird.Promise.promisifyAll(ModelTest)
ModelTest.on('construct', function(doc) {
  bluebird.Promise.promisifyAll(doc)
})

bluebird.coroutine(function* () {
  const array = yield ModelTest.findAsync({})

  const one = yield ModelTest.findOneAsync({ _id: '132456897' })
  one.name = 'Test'
  yield one.saveAsync()
})()


```
