### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by bebejane** [Ivshti/linvodb3#4]
I am getting this error on mac osx 10.9.5 when trying to open my database.

Uncaught OpenError: EMFILE: too many open files, open '/Users/bjorn/Library/Application Support/xxxxxx/data/sales_documents.db/38.medea.hint'

I have been trying to increase the max open files with ulimit -n 2048 with no success.
 
Im not sure if this is caused by the LinvoDB module or medeadown.

**Comment by Ivshti** [comment]
Hello, this is a Medea issue. 
I've seen it at certain times, but I think it shouldn't happen if you compact your DB often

```javascript
Doc.store.db.db.compact(function(err) { if (err)console.error(err) })
```

Also, if your application is data-intensive consider using LevelDB as a back-end.

Hope that solves the issue.

**Comment by bebejane** [comment]
Thanks. Switching to LevelDB worked for me. 

I was looking for the compact function but i could never find it, still cant see it the way you referenced it above.

**Comment by Ivshti** [comment]
If Doc is the constructor given by LinvoDB, then the compact is in Doc.store.db.db.compact. Doc.store is effectively the MedeaDOWN store, which wraps Medea (.db) which has a another .db division which has a compact.
