### ISSUE TITLE
Have deleted data appeared after the restart the computer

### ISSUE THREAD

**Issue by SlamDunkDcc** [Ivshti/linvodb3#43]
I have to add data and delete data,And the operation was successful.But when I restart the computer after, the first retrieval of these data have been deleted.The second retrieval, has been deleted data is not appear again.It can happen to every time to restart the computer.

**Comment by SlamDunkDcc** [comment]
When I user this 
var i = 0;
Planet.store.createReadStream().on("data", function () {
    i++
}).on("end", function () {
    console.log(i)
});

first result is 81,the second time is 31. After the result is always 30(30 is the correct)

**Comment by SlamDunkDcc** [comment]
@Ivshti Do you know the reason? Thanks

**Comment by Ivshti** [comment]
@SlamDunkDcc what back-end store are you using? We always have to begin with that

**Comment by SlamDunkDcc** [comment]
@Ivshti I used medeadown. 

var LinvoDB = require("linvodb3");
LinvoDB.defaults.store = {db: require("medeadown")};


I only know this back-end store, Can you tell me the other back-end store. Thanks very much

**Comment by SlamDunkDcc** [comment]
When I use LinvoDB.defaults.store = {db: require("leveldown")};

Error: A dynamic link library (DLL) initialization routine failed.
G:\Work\Projects\LinvoTest\node_modules\leveldown\build\Release\leveldown.node

**Comment by Ivshti** [comment]
@SlamDunkDcc leveldown requires compilation, so it's tricky; try to run in node.js or google how to build native modules for Electron

I suggest, if you're using electron, try level-js

**Comment by SlamDunkDcc** [comment]
@Ivshti I had tried level-js, but have not found this problem.
I am running in NW,so i can't use leverdown?

In the case of  "medeadown" ,if there has only servel items,this problem almost won't appear.But after the operation several times to add and delete data, almost every time to restart will appear the problem.

I will try the level-js later, and if i can't resolve the problem, i have to change the way to sava data
/(ㄒoㄒ)/~~

**Comment by Ivshti** [comment]
@SlamDunkDcc you can use leveldown, but you have to compile it right. Google "compiling native node.js modules for nw.js"

**Comment by SlamDunkDcc** [comment]
When I was in edit last one found you already closed...

**Comment by Ivshti** [comment]
@SlamDunkDcc so does level-js not solve it?

**Comment by SlamDunkDcc** [comment]
@Ivshti
First of all thank you very much for your answer patiently

level-js may can solve it, I mean if change will cost a lot of time

Did you find out the questions about "medeadown"?

**Comment by SlamDunkDcc** [comment]
On the premise of me a lot of testing, I think this is a bug

**Comment by jishuo1213** [comment]
@Ivshti
I build leveldown successfully use nw-gyp,but when i use as follow:

```
      var LinvoDB = require("linvodb3");

    LinvoDB.defaults.store = {db: require("leveldown")}; 

    LinvoDB.dbPath = process.cwd();
    var Planet = new LinvoDB("planeta", {/* schema, can be empty */})
    Planet.find({}).exec(function (err, docs) {

        console.info(docs)
    });
```
I got an error as follow:

` nwjs-v0.12.1-win-ia32\node_modules\linvodb3\node_modules\levelup\lib\levelup.js:115 Uncaught TypeError: object is not a function`

In levelup.js line 115

`  db           = dbFactory(this.location)`

I don't konw this error is cause by linvodb3 or the leveldown.node file I build.

**Comment by SlamDunkDcc** [comment]
@Ivshti   You said "compiling native node.js modules for nw.js". Is the compiler "leveldown.node"?

**Comment by Ivshti** [comment]
@SlamDunkDcc no
https://github.com/nwjs/nw.js/wiki/using-node-modules#3rd-party-modules-with-cc-addons

**Comment by SlamDunkDcc** [comment]
@Ivshti  
https://github.com/nwjs/nw.js/wiki/using-node-modules#3rd-party-modules-with-cc-addons
I was do as this...
