### ISSUE TITLE
How to stop an event listener?

### ISSUE THREAD

**Issue by mbalex99** [Ivshti/linvodb3#49]
I'm listening to some data using 

```javascript
MyModel.on('inserted', function(docs){
    console.log(`inserted docs`, docs);
});
```

How do I stop listening to this static handler?

**Comment by Ivshti** [comment]
Models extend on EventEmitter, so you just have to do `removeListener`:
https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener
