### ISSUE TITLE
Multiple Stores

### ISSUE THREAD

**Issue by NicholasJohn16** [Ivshti/linvodb3#5]
Is it possible to have multiple data stores in Linvodb like NeDB? How would you go about selecting the different data stores?

I guess you could just use different file names for different stores or is there a better option?

**Comment by Ivshti** [comment]
Of course. Just create more than one models with the constructor. See the docs, the first argument is the model name which also identifies the storage name. You can override Linvodb.dbPath, which is the root dir for all stores, but full control over every individual path is not recommended as this depends on the backend store.
