### ISSUE TITLE
 Why should I use it very slow？

### ISSUE THREAD

**Issue by milu2003** [Ivshti/linvodb3#50]
My data is just a few thousand。

**Comment by Ivshti** [comment]
not helpful in any way, no details

plus, performance depends largely on the back-end store you're using

**Comment by milu2003** [comment]
@Ivshti  i use it in electron.
no back-end store。

**Comment by Ivshti** [comment]
you can't possibly use it without a back-end store, as linvodb3 cannot be used without a back-end store
