### ISSUE TITLE
when using level-js , LinvoDB.dbPath setting not work，is that correct？

### ISSUE THREAD

**Issue by FengNongtheWindCoder** [Ivshti/linvodb3#55]
i switched from leveldown to level-js
dbPath setting works fine with leveldown,but doesn't seem to work with level-js
this is what i wrote,just like the code in readme file
```
LinvoDB = require("linvodb3");
LinvoDB.defaults.store = {
    db: require("level-js")
}; // Comment out to use LevelDB instead of level-js
LinvoDB.dbPath = path.join(rootpath, 'db');//rootpath is the path of my program
```
the db files  should be  under my program folder ，but i found them under “C:\Users\xxxx\AppData\Roaming\xxxx\IndexedDB”
is this correct？or can i change the db files folder when using level-js？

**Comment by Ivshti** [comment]
This is absolutely correct behaviour. Level-js is an abstraction on top of IndexedDB, which does not allow you to change paths. The path here is considered, but on a higher level than an actual path. If you open the indexeddb inside your browser debugger you'll see that the values are indeed beginning with the path, but it won't reflect the actual real FS path

**Comment by FengNongtheWindCoder** [comment]
thanks for your quick reply，switch back to leveldown now。
