### ISSUE TITLE
Odd Capitalization Issue

### ISSUE THREAD

**Issue by NicholasJohn16** [Ivshti/linvodb3#6]
This may be my noobness, but I'm having an odd issue with capitalization. I've created a database where I'm storing the path for each file. That path is like this:
```
I:\path\to\file\image.png
```
but when it's getting stored, the drive is lowercase:
```
i:\path\to\file\image.png
```
I'm not exactly sure why this is happening and it doesn't really bother me, except that it's not consistent when I'm doing queries. So when I'm iterating over my files to make sure no new ones have been added, it's not finding them cause the drive letters don't match. I know I can just make the first letter lowercase, but not sure what kind of effect that'll have on Unix platforms so I'm just wondering if there's a way to fix this in general?

Thanks for any assistance.

**Comment by Ivshti** [comment]
This is indeed really weird. Can you give me a sample code of how you're doing the storing?

**Comment by NicholasJohn16** [comment]
Here's a snippit of my code. It's a bit of a mess right now. I scan a directory, iterate of the files, each file is added to a `async.queue` and processed where it's stored in the database.
```
linvoDB.defaults.store = {db: require('medeadown')};
linvoDB.dbPath = gui.App.dataPath;

var File = new linvoDB('file', {} );

function scanDirectory(dir, queue, end, recursive) {

	fs.readdir(dir,function(err,files) {

		if(err) {
			callback(err);
		}
					
		files.forEach(function(file) {
			var filePath = path.join(dir, file);
			console.log(filePath);
			
			fs.stat(filePath, function(err, stats) {
			
				if(err) {
					console.log(err);
				}
				
				if(recursive && stats && stats.isDirectory()) {
					scanDirectory(filePath, queue, end, recursive);
				} else if (stats.isFile()) {
					File.findOne({'path': filePath} , function(err, foundFile) {
						
						if(err) {
							console.log(err);
						}

						if(!foundFile) {
							queue.push({'path': filePath, 'stats': stats}, end);
						}
					});
				}
			});
		});
	});
}

var queue = async.queue(function(file, callback) {
	var hash = crypt.createHash('md5');
	var stream = fs.createReadStream(file.path);
	var thumb = null;
	
 	stream.on('data',function(data) {
		hash.update(data,'utf8');
 	});
		
	stream.on('end',function() {
		var md5 = hash.digest('hex');
		var scale = null;

		var newFile = new File(file.stats);
		newFile.md5 = md5;
		newFile.path = file.path;	
		newFile.save();
		
		callback();
	});
},10);
```

**Comment by NicholasJohn16** [comment]
This issue seems to have resolved itself. Not sure why, but it seems to be working now.

**Comment by Ivshti** [comment]
All tests except two un-implemented pass - if data was tolowercased somehow it would be caught by the tests 

The issue could be in the backend store you are using, but I doubt that too. Is it possible that your OS returns data in an inconsistent format? I know it sounds ridiculous but it's one of the few explanations left
