### ISSUE TITLE
Default store is undefined

### ISSUE THREAD

**Issue by brunocascio** [Ivshti/linvodb3#7]
Hi, i trying to use linvoDB with Electron, but when add this line

`LinvoDB.defaults.store = { db: require("medeadown") };`

I got output: `TypeError: LinvoDB.defaults.store is not a function` 

In the code `LinvoDB.defaults` only has `autoLoad` and `autoIndex` attributes.

**Comment by Ivshti** [comment]
Hello. This smells like a syntax error in your own code. There is no calling of "defaults.store", let alone "LinvoDB.defaults.store" in LinvoDB, so there is no way it could generate that error.

Make sure the snippet is exactly the one you pasted
```javascript
LinvoDB.defaults.store = { db: require("medeadown") };
```
