### ISSUE TITLE
Distribute database 

### ISSUE THREAD

**Issue by flamusdiu** [Ivshti/linvodb3#76]
I was looking at doing Electron with linvodb3. Is there a way to ship a pre-filled database?

**Comment by flamusdiu** [comment]
From what I can tell, there isn't a way to write the DB outside of the webpage (see: http://stackoverflow.com/a/35142175). Distributing a pre-filled database would not work.

I could use an form interface to load documents into the DB (in the form of Markdown)  for testing.

Is there a way to read a local folder to populate the database? I guess I would need to add documents to something like `src\app\docs` then move that folder over when it's built.

I require the whole project to be completely offline.

**Comment by flamusdiu** [comment]
I cannot read local files directly. The only choice I have is HTTP requests to get each file. I really don't want/need to do this. Looks like I am at a stand still. =(

**Comment by Ivshti** [comment]
I think this is kind of out of scope. LinvoDB3 is an abstraction to any leveldown compatible store, so you should either change store to something that allows an offline database to be shipped or indeed pull the files at init time somhow

how big are the files?

**Comment by flamusdiu** [comment]
Not sure how big they will be. Probably mostly smaller ones. I created a NodeJS custom command to run and migrate the files from X format to markdown to use in the DB. Then I was converting Markdown -> HTML. 

Reasoning for this is because Markdown is similar to write if I was to generate a doc directly then other formats. I have some existing documents that I need to transition over which are a bit large but those shouldn't be that much.

I have considered PouchDB which might work. Thoughts?

**Comment by flamusdiu** [comment]
Looks like I am going to use Pouchdb. I rewrote https://github.com/gr2m/spawn-pouchdb-server to work for me as well. Thanks for the support!
