### ISSUE TITLE
linvodb3 does not install well on npm5...

### ISSUE THREAD

**Issue by mitsos1os** [Ivshti/linvodb3#83]
Trying to install on an empty folder with **node v8.7.0** and **npm v5.4+** installs correctly the module and its dependencies but fails to insert **bagpipe** in **package-lock.json** created...

so in next install where **package-lock.json** exists, the bagpipe is not installed, so linvodb3 is not working and crashing during require...

Bug also submitted to npm [here](https://github.com/npm/npm/issues/18892)

**Comment by harryparkdotio** [comment]
just `npm i bagpipe` to install bagpipe, that should get it working. (At least it did get it working for me)

**Comment by mitsos1os** [comment]
Of course this is something that works. But the reason for this issue is to highlight the issue of package structure incompatibility with latest npm releases

**Comment by mitsos1os** [comment]
Anyone dealing with this?? It is quite a serious problem with production deployments that use **package-lock.json**. Until npm actually resolve this issue, a workaround would be using different kind of dependencies... maybe referencing commit hash? I will try and  check if this works as a *messy* workaround

**Comment by mitsos1os** [comment]
It seems that directly referencing the commit number it is correctly setup in package-lock.json. So please accept merge request in order to fix this at least temporarily

**Comment by mitsos1os** [comment]
You will have to replace the version in npm...

**Comment by mitsos1os** [comment]
Hi I tried reinstalling today from npm and it still hasn't got the change in the package.json... Have you deployed the change? Or if you find it more appropriate maybe also up the package.json version number by patch to 3.25.1?
