### ISSUE TITLE
I can't get nw.js to load the code example database

### ISSUE THREAD

**Issue by hamoy** [Ivshti/linvodb3#9]
I get the error below every time I open my app in nw.js, I am using the code right from example page. Am I missing something or is this a issue with nw.js? Thank you!

Uncaught node.js Error 

OpenError: doc.db: No such file or directory
    at eval (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.XLDg8g/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:118:34)
    at eval (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.XLDg8g/node_modules/medeadown/medeadown.js:28:14)
    at eval (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.XLDg8g/node_modules/medeadown/node_modules/leveldown-open/leveldown-open.js:15:18)
    at Object.cb [as oncomplete] (fs.js:158:19)

This is the code:

var LinvoDB = require("linvodb3");
LinvoDB.defaults.store = { db: require("medeadown") }; // Comment out to use LevelDB instead of Medea

var Doc = new LinvoDB("doc", { /* schema, can be empty */ })

 	// Construct a single document and then save it
var doc = new Doc({ a: 5, now: new Date(), test: "this is a string" });
doc.b = 13; // you can modify the doc 
doc.save(function(err) { 
    // Document is saved
    console.log(doc._id);
});

// Insert document(s)
// you can use the .insert method to insert one or more documents
Doc.insert({ a: 3 }, function (err, newDoc) {
    console.log(newDoc._id);
});
Doc.insert([{ a: 3 }, { a: 42 }], function (err, newDocs) {
    // Two documents were inserted in the database
    // newDocs is an array with these documents, augmented with their _id

    // If there's an unique constraint on 'a', this will fail, and no changes will be made to the DB
    // err is a 'uniqueViolated' error
});

// Save document(s)
// save is like an insert, except it allows saving existing document too
Doc.save([ doc, { a: 55, test: ".save is handy" } ], function(err, docs) { 
    // docs[0] is doc
    // docs[1] is newly-inserted document with a=55 and has an assigned _id

    // Doing that with .insert would throw an uniqueViolated error for _id on doc, because it assumes all documents are new
});

**Comment by Ivshti** [comment]
I think that was an issue with medeadown not creating the storage folder by default, but I cannot remember right now how to fix it.

Can you try to make the directory manually - e.g.
```javascript
LinvoDB.dbPath = "/tmp";
```
And create a directory named doc.db in /tmp

**Comment by hamoy** [comment]
It worked with explicitly defining the directory i.e. "/tmp".  So it appears it wasn't picking up the app directory. I tried it both on Windows and on a Mac

It worked without me needing to create the doc.db file.

Now I am encountering another issue with nw.js, I will post in a new threat.
