### ISSUE TITLE
I want to know if linvodb3 supports browser

### ISSUE THREAD

**Issue by fullee** [Ivshti/linvodb3#98]
I know that nedb supports browsers, using indexedDb, websql. . .
If linvodb3 supports the browser side, how can I use it?

May not be fluent, I am translating via google

**Comment by Ivshti** [comment]
yes, this module works via `localforage` which can work via localstorage

here's a browserify example: https://github.com/Ivshti/linvodb3/blob/master/sample/browserify.sh

**Comment by fullee** [comment]
感谢
